#!/usr/bin/env python

import sys
import numpy as np
import pandas as pd
import argparse

import exofop
import hoshi

parser = argparse.ArgumentParser(description="Query the stellar parameters of Mamajek & Pecaut (2013)")
parser.add_argument('--color', help='Color to query by', type=str, default='V-Ks')
parser.add_argument('--epic', help='EPIC ID number', type=int)

args = parser.parse_args()

color = args.color
epic = args.epic


if color == 'B-V':
    m_str = 'V'
elif color == 'V-Ks':
    m_str = 'V'
elif color == 'J-H':
    m_str = 'J'
elif color == 'H-K':
    m_str = 'K'
elif color == 'Ks-W1':
    m_str = 'K'

try:
    phot = exofop.get_phot(epic, verbose=False)
except:
    print "Error retrieving photometry"
    sys.exit()

try:
    a,ua = phot[a_str]
    b,ub = phot[b_str]
    c, uc = a-b, np.sqrt(ua**2 + ub**2)
    print "{0} = {1:.3f} +/- {2:.3f}".format(color, c, uc)
    m = phot[m_str][0]
except:
    print "Error reading photometry"
    sys.exit()

try:
    mamajek = hoshi.Mamajek()
    mamajek.query(color, c, uc, m)
except:
    print "Error with query"
    sys.exit()
